resources:
- ../base

namePrefix: dev-
namespace: dev

images:
- name: hello-api
  newName: ksangdej/hello-api

replicas:
- count: 1
  name: dev-hello-api-deploy
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
